# Generated by Django 5.0.8 on 2025-09-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Author username', max_length=100)),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('content', models.TextField(help_text='Post content')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
