# Generated by Django 5.0.8 on 2025-09-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the commenter', max_length=100)),
                ('content', models.TextField(help_text='Comment content')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the user who liked', max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='When the like was created')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-created_datetime'],
                'unique_together': {('post', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the user who shared', max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='When the share was created')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
                'ordering': ['-created_datetime'],
                'unique_together': {('post', 'username')},
            },
        ),
    ]
