# Generated by Django 5.0.8 on 2025-09-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_like_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, help_text='Original post if this is a shared post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('original', 'Original Post'), ('shared', 'Shared Post')], default='original', help_text='Type of post', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='share_comment',
            field=models.TextField(blank=True, help_text='Additional comment when sharing'),
        ),
        migrations.AlterField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_actions', to='posts.post'),
        ),
    ]
