site_name: SocialHubAPI Documentation
site_description: Complete social API with CRUD operations for posts and social interactions
site_author: SocialHubAPI Team
site_url: https://socialhubapi.example.com

# Repository
repo_name: socialhubapi
repo_url: https://github.com/lfelipediniz/SocialHubAPI
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

# Navigation
nav:
  - Home: index.md
  - API Reference:
    - Routes Reference: api/routes.md
    - Posts API: api/posts.md
    - Users API: api/users.md
    - Social Features: api/social.md
  - Authentication: auth/index.md
  - Quick Start: quickstart.md
  - Development: development.md
